const SeriesData = [
 
  {
    title : "Kurulus Osman",
    src :"./images/osman.png",
    rating : " 10/10",
    discription :"The series Kuruluş: Osman follows the life of Osman I, the founder of the Ottoman Empire",
    cast : "Burak Özçivit , Ozge Törer, Nurettin Sönmez",
    genre : " Historical,adventure,love story🌹🌸",
    link : "https://play.niazitv.pk/dramas?genre=9",
  },
  {
    title : "Ates Kuslari ",
     src :"./images/ates.png",
     rating : " 10/10",
     discription : "The series Ateş Kuşları (Firebirds) follows the dramatic and intense lives of a group of street children who form a tight-knit family",
     cast :"Hazar Ergüçlü, Ekin Koç,Biran Damla Yılmaz ",
     genre : "emotional💔,love story🌹🌸",
     link : "https://play.niazitv.pk/dramas?genre=43",
  },
  {
    title : "Sultan Salahuddin Ayyubi",
    src:"./images/ayyubi.jpg",
    rating : " 10/10",
    discription : "The series Sultan Salahuddin Ayyubi portrays the legendary life and conquests of,his role in the Crusades",
    cast : "Cengiz Coşkun,Kadir Doğulu , Neslihan Atagül, Hüseyin Avni Danyal ",
    genre : " Historical Drama ,conquer",
    link : "https://play.niazitv.pk/drama/58/salahuddin-ayyubi-series",
  },
  {
    title : "The Pit (Cukur) ",
    src :"./images/cukur.png",
    rating : " 10/10",
    discription :"The series Çukur (The Pit) revolves around a notorious neighborhood in Istanbul, controlled by the powerful Koçovalı crime family" ,
    cast  : "Aras Bulut İynemli,Elçin Sangu ,Aksel Bonfil ,Dilan Çiçek Deniz",
    genre : " crime Drama",
    link : "https://play.niazitv.pk/dramas?genre=26",
  },
  {
    title : "Teskilat",
    src :"./images/teskilat.jpg",
    rating : " 10/10",
    discription : "The series Teşkilat centers on a team of elite Turkish intelligence agents",
    cast : "Çağatay Ulusoy ,Hazar Ergüçlü,Sarp Akkaya",
    genre : "action ,love story🌹🌸,fight",
    link : "https://play.niazitv.pk/dramas?genre=18",
  },
  {
    title : "Uyanis: Buyuk Selcuklu",
    src :"./images/uanis.jpg",
    rating : " 9/10",
    discription : "The series Uyanış: Büyük Selçuklu  depicts the rise and consolidation of the Seljuk Empire.",
    cast : "Buğra Gülsoy ,Elçin Sangu ,Cengiz Coşkun",
    genre : " Historical,love story🌹🌸,mystery",
    link : "https://play.niazitv.pk/drama/9/uyanis-buyuk-selcuklu-nizaam-e-alam-in-urdu",
  },
  {
    title :"Ertugrul Ghazi",
    src : "./images/ertugrul.png",
    rating : "9/10",
    discription : "The series Diriliş: Ertuğrul follows the legendary life of Ertuğrul Bey, the father of Osman I",
    cast : "Engin Altan,Esra Bilgiç, Kaan Taşaner, Hülya Darcan",
    genre : "Historical,adventure,love story🌹🌸",
    link : "https://play.niazitv.pk/dramas?genre=8"
  },
  {
    title : "Mehmed: Fetihler Sultani",
   src :"./images/mehmad.jpg",
   rating : " 7.8/10",
   discription : "The series Sultan Mehmed Fatih (Mehmed the Conqueror) highlights the life and conquests of Sultan Mehmed II,",
   cast :"Kenan İmirzalioğlu ,Cansu Dere ,Hakan Boyav",
   genre : " Historical,conquer,love story🌹🌸",
   link : "https://play.niazitv.pk/drama/62/mehmed-fetihler-sultani",
  },
  {
    title : "Sultan Alp Arslan",
    src :"./images/Alparslan.png",
    rating : " 7.8/10",
    discription : "The series Sultan Alp Arslan chronicles the life and reign of the formidable Seljuk Sultan Alp Arslan",
    cast : "Fahriye Evcen,Baran Akbulut, Sedef Avcı, Uğur Yücel ,Serdar Gökhan",
    genre : " Historical.love story🌹🌸,action",
    link : "https://play.niazitv.pk/drama/27/alparslan-buyuk-selcuklu-season-2",
  },
  {
    title : "Barbaroslar ",
    src :"./images/barbar.jpg",
    rating : " 5.1/10",
    discription : "The series Barbaroslar depicts the epic adventures of the Barbarossa brothers during the 16th century.",
    cast : "Engin Altan Düzyatan ,Ulaş Tuna Astepe",
    genre : " Historical adventure,love story🌹🌸,mystery",
    link : "https://play.niazitv.pk/dramas?genre=14",
  },
  {
    title : "Destan",
    src : "./images/destan.jpg",
    rating : "5.1/10",
    discription : "The series Destan follows the epic journey of a fierce warrior woman in the pre-Islamic Turkic world.",
    cast : "Ebru Şahin ,Edip Tepeli,Selim Bayraktar, Deniz Barut ,Burak Tozkoparan",
    genre : " Historical Fantasy,mystery,love story.",
    link : "https://play.niazitv.pk/drama/28/destan-season-1"
  },
  {
    title : "Mendirman Jaloliddin ",
    src:"./images/jalaldin.jpg",
    rating : " 5/10",
    discription : "The series Mendirman Jalaluddin chronicles the life of Jalal al-Din Khwarazmshah, the last ruler of the Khwarazmian Empire",
    cast : "Ekin Koç ,Bergüzar Korel ,Kadir Doğulu",
    genre : " Historical,love story🌹🌸,mystery",
    link : "https://play.niazitv.pk/dramas?genre=24",
  },

]
export default SeriesData;